# Generated by Django 4.2.3 on 2023-08-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_api', '0003_gig_delivery_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
