# Generated by Django 4.2.3 on 2023-07-20 14:11

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.SlugField(blank=True, max_length=150, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('likes', models.IntegerField()),
                ('status', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft'), ('inactive', 'Inactive')], default='draft', max_length=30)),
                ('link', models.SlugField(blank=True, max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField()),
                ('skills', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), size=8), size=8)),
                ('link', models.SlugField(blank=True, max_length=150, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('public_review', models.TextField(max_length=500, verbose_name='Description')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='market_api.buyer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Total Amount')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('incomplete', 'Incomplete'), ('in progress', 'In Progress'), ('delivered', 'Delivered'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('dispute', 'Dispute'), ('late', 'Late')], default='in progress', max_length=30)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyers', to='market_api.buyer')),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gigs', to='market_api.gig')),
            ],
            options={
                'ordering': ['total_amount', 'order_date'],
            },
        ),
        migrations.CreateModel(
            name='GigRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500, verbose_name='Description')),
                ('max_budget', models.DecimalField(decimal_places=2, max_digits=7)),
                ('flexible_budget', models.BooleanField()),
                ('status', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft'), ('disapproved', 'Diapproved'), ('inactive', 'Inactive')], default='draft', max_length=30)),
                ('link', models.SlugField(blank=True, max_length=150, unique=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gigs', to='market_api.buyer')),
            ],
        ),
        migrations.AddField(
            model_name='gig',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gigs', to='market_api.seller'),
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Bid Amount')),
                ('bid_date', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
                ('gig_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gig_requests', to='market_api.gigrequest')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='market_api.seller')),
            ],
            options={
                'ordering': ['amount', 'bid_date'],
            },
        ),
    ]
